version: "3"

services:
  api-postgres:
    image: bitnami/postgresql
    ports: 
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - nPOSTGRESQL_DATABASE=app